### ISSUE TITLE
Vagrant credentials

### ISSUE THREAD

**Issue by Deepthi-Chand** [SEL-Columbia/formhub#1336]
hi,
I'm trying to run formhub instance on my virtual box. I got the vdi from the given link (https://s3.amazonaws.com/PublicVDIs/Formhub-Public-VDI-v.0.0.2.vdi.bz2). when I'm trying to start the box, its asking for login credentials. Are the credentials mentioned some where or am I doing something wrong.

**Comment by Jonathan727** [comment]
I'm having the same issue.

**Comment by vr2262** [comment]
See if the discussion in #1349 solves your issue.

**Comment by Jonathan727** [comment]
thanks!
