### ISSUE TITLE
VirtualBox install manual does not state the login password

### ISSUE THREAD

**Issue by BenjaminKobjolke** [SEL-Columbia/formhub#1349]
I followed the [install guide](https://github.com/SEL-Columbia/formhub/wiki/How-To-Run-Your-Own-Formhub-Virtual-Machines-on-VirtualBox) but what is the password for debian login fhuser ?

**Comment by camoncal** [comment]
I can't find where is the password for fhuser. I already tried typing fhuser as user and password, but it says that the credentials are invalid. Can somebody help me with this inquire. Thank you!

I downloaded the VDI, to run it using VM.

**Comment by vr2262** [comment]
As @prabhasp mentioned, the password is given in this section:

https://github.com/SEL-Columbia/formhub/wiki/How-To-Run-Your-Own-Formhub-Virtual-Machines-on-VirtualBox#configure-outgoing-email

> Once the VM has booted, login at the prompt as either user `root`, or `fhuser` and then use `sudo` to become root.
> 
> The password for both accounts is set to **all4one** but you should change those using the [passwd](http://linux.die.net/man/1/passwd) command, later.

**Comment by camoncal** [comment]
Thank you so much!, I am sorry I haven´t seen it.
