### ISSUE TITLE
How to HTTPS the traffic? (Running my own Formhub on AWS)

### ISSUE THREAD

**Issue by amjad-shurbaji** [SEL-Columbia/formhub#1354]
Hello everyone, first i have to say that i'm fascinated with the work you'd accomplished building the formhub :) It's really helpful and great tool!
I configured my own formhub instance using Amazon Web Services. Everything is just working fine and smooth, except for one thing, it only work under HTTP not HTTPS. I have the required certificates but i couldn't find a way to append it to the instance (i'm not very much familiar with linux)
Is there any way to do it? Please help because it's a very sensitive issue for my business :)
Thanks in advance guys!

**Comment by vr2262** [comment]
Strictly speaking Formhub is no longer maintained. We are currently working on the next generation of Formhub at https://github.com/SEL-Columbia/dokomoforms

If you still want to use Formhub, according to the wiki you just need to adjust your AWS settings to enable HTTPS access:

https://github.com/SEL-Columbia/formhub/wiki/How-To-Run-Your-Own-Formhub-Virtual-Machines-on-VirtualBox

I'm not sure whether the documentation is correct or sufficient, however...

You may also need to adjust your server settings to listen to HTTPS traffic on port 443.
