### ISSUE TITLE
Command doesn't accept any arguments

### ISSUE THREAD

**Issue by adisadit** [SEL-Columbia/formhub#1358]
Hi i want build formhub in my local server and when i'm moved to step `python manage.py syncdb migrate` i got this error:

```
Your environment is:"formhub.preset.default_settings"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 384, in handle
    raise CommandError("Command doesn't accept any arguments")
CommandError: Command doesn't accept any arguments
```

Do you guys know what caused this?

I'm using Django 1.5 here and I only change password in default_setting.py from foo into my desired password
`DATABASES['default']['PASSWORD'] = 'foo'` to `DATABASES['default']['PASSWORD'] = 'formhub'`

Do i need to assign DATABASES name and PASSWORD also?

Any help for this gladly appreciated

**Comment by vr2262** [comment]
Strictly speaking Formhub is no longer maintained. We are currently working on the next generation of Formhub at https://github.com/SEL-Columbia/dokomoforms

If you still want to use Formhub, I can try to look into what the problem is...

Which guide are you following?

**Comment by adisadit** [comment]
I'm using this guide https://github.com/SEL-Columbia/formhub/blob/master/docs/install/README.md and i'm currently at last part in steps number 5.

Thank you for pointing me to the new formhub. I will look at the link.

**Comment by vr2262** [comment]
From a quick glance it looks like you need to run

```
$ python manage.py syncdb --noinput
```

and

```
$ python manage.py migrate
```

as separate commands. Did you do it this way?

**Comment by adisadit** [comment]
Yes i run as separate commands. But when i tried to run the last command 'python manage.py migrate' it appeared like that

**Comment by vr2262** [comment]
I found this after searching for a while... not sure if it's helpful:

https://stackoverflow.com/questions/15454008/how-to-reset-db-in-django-i-get-a-command-reset-not-found-error

**Comment by adisadit** [comment]
Hi @vr2262 thank you for your help. Apparently this error caused by my mistake by using `syncdb migrate` not just `migrate`. I will close this issue now.

Thanks again for your help!

**Comment by vr2262** [comment]
@adissadis no problem! I'm glad I could help.
